[metadata]
name = manuka
author = ARDC Nectar Cloud Services
author_email = coreservices@ardc.edu.au
license = Apache-2.0
summary = User management for the Nectar Research Cloud
description_file =
    README.md
keywords = manuka
home_page = https://github.com/NeCTAR-RC/manuka
classifier =
    Environment :: OpenStack
    Intended Audience :: Information Technology
    Intended Audience :: System Administrators
    License :: OSI Approved :: Apache Software License
    Operating System :: POSIX :: Linux
    Programming Language :: Python
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.12

[files]
packages = manuka
include_package_data = True

[entry_points]
console_scripts =
    manuka-api = manuka.cmd.api:main
    manuka-worker = manuka.cmd.worker:main
    manuka-manage = manuka.cmd.manage:cli

manuka.notifier =
    logging = manuka.worker.notifier:LoggingNotifier
    taynac = manuka.worker.notifier:TaynacNotifier

oslo.config.opts =
    manuka = manuka.config:list_opts
oslo.policy.policies =
    manuka = manuka.common.policies:list_rules
oslo.policy.enforcer =
    manuka = manuka.policy:get_enforcer

[pbr]
skip_changelog=true
skip_authors=true
