#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#
"""Add expiry attributes to user

Revision ID: 1eb4f4f09e3b
Revises: 3840b8c7f97d
Create Date: 2021-01-14 16:33:01.302537

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "1eb4f4f09e3b"
down_revision = "3840b8c7f97d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("expiry_next_step", sa.Date(), nullable=True)
    )
    op.add_column(
        "user", sa.Column("expiry_status", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "expiry_status")
    op.drop_column("user", "expiry_next_step")
    # ### end Alembic commands ###
