"""make user_id unique

Revision ID: 4b8f295e23e2
Revises: 53c5ca8ba141
Create Date: 2020-04-30 15:58:32.976300

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '4b8f295e23e2'
down_revision = '53c5ca8ba141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
