"""Add active flag to user

Revision ID: ae500d7e95d1
Revises: 3840b8c7f97d
Create Date: 2021-01-13 11:10:39.289555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae500d7e95d1'
down_revision = '3840b8c7f97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active')
    )
    # ### end Alembic commands ###
