"""Add invitation table

Revision ID: be05c858ea9e
Revises: 3840b8c7f97d
Create Date: 2020-05-21 16:42:34.679247

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'be05c858ea9e'
down_revision = '3840b8c7f97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitation')
    # ### end Alembic commands ###
