"""Add terms object

Revision ID: e4a54358b0fe
Revises: 1eb4f4f09e3b
Create Date: 2021-01-19 16:01:57.248461

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e4a54358b0fe'
down_revision = '1eb4f4f09e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terms',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('issued', sa.Date(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('terms')
    # ### end Alembic commands ###
