"""Initial migration.

Revision ID: 52e8555a0886
Revises: 
Create Date: 2020-04-08 16:20:24.783622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e8555a0886'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('persistent_id', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('displayname', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('state', sa.Enum('new', 'registered', 'created'), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('terms_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('terms_version', sa.String(length=64), nullable=True),
    sa.Column('shibboleth_attributes', sa.PickleType(), nullable=True),
    sa.Column('ignore_username_not_email', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.String(length=250), nullable=True),
    sa.Column('surname', sa.String(length=250), nullable=True),
    sa.Column('phone_number', sa.String(length=64), nullable=True),
    sa.Column('mobile_number', sa.String(length=64), nullable=True),
    sa.Column('home_organization', sa.String(length=250), nullable=True),
    sa.Column('orcid', sa.String(length=64), nullable=True),
    sa.Column('affiliation', sa.Enum('faculty', 'student', 'staff', 'employee', 'member', 'affiliate', 'alum', 'library-walk-in'), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('persistent_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
