"""change user_id to keystone_user_id

Revision ID: e9e502fdd76f
Revises: 4b8f295e23e2
Create Date: 2020-04-30 16:24:11.575667

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e9e502fdd76f'
down_revision = '4b8f295e23e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_id',
                    new_column_name='keystone_user_id',
                    existing_type=sa.String(64),
                    nullable=True,
                    unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'keystone_user_id',
                    new_column_name='user_id',
                    existing_type=sa.String(64),
                    nullable=True,
                    unique=True)
    # ### end Alembic commands ###
